version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    assignees:
      - 'davealaw'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    groups:
      # Group Electron-related updates
      electron:
        patterns:
          - 'electron*'
        update-types:
          - 'minor'
          - 'patch'

      # Group testing-related updates
      testing:
        patterns:
          - 'jest*'
          - '@babel/*'
          - 'babel-*'
        update-types:
          - 'minor'
          - 'patch'

      # Group linting/formatting updates
      code-quality:
        patterns:
          - 'eslint*'
          - 'prettier*'
          - 'husky*'
          - 'lint-staged*'
        update-types:
          - 'minor'
          - 'patch'

    # Ignore major version updates for core dependencies
    ignore:
      - dependency-name: 'electron'
        update-types: ['version-update:semver-major']
      - dependency-name: 'kokoro-js'
        update-types: ['version-update:semver-major']

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:30'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    assignees:
      - 'davealaw'
    commit-message:
      prefix: 'ci'
      include: 'scope'
